name: Deploy dbt to Production

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    # Required permissions for WIF authentication
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # 1. Authenticate to Google Cloud using Workload Identity Federation
      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: 'projects/762399742717/locations/global/workloadIdentityPools/github-pool/providers/github-provider'
          service_account: 'dbt-project@dbtproject-507217.iam.gserviceaccount.com'

      # 2. Set up Python Environment
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # 3. Install dbt and adapter
      - name: Install dbt
        run: pip install dbt-bigquery

      # 4. Install dbt packages
      - name: Install packages
        run: dbt deps

      # 5. Validate dbt project structure
      - name: Validate project
        run: dbt parse

      # 6. Deploy and run dbt in Production
      - name: Deploy to PROD
        env:
          GOOGLE_PROJECT_ID: 'dbtproject-507217'
        run: |
          # Authenticating natively using the environment credentials generated by the auth action
          dbt build --target prod --profiles-dir .
